### ISSUE TITLE
Add another withdraw method to allow ETH transfer directly to other address

### ISSUE THREAD

**Issue by jdkanani** [gnosis/pm-contracts#103]
It would be easy for plasma like a contract to use WETH, if `EtherToken.sol` can add `withdraw(uint value, address user)` method.

This change will reduce transfer ETH easy by doing - 

```js
WETH(wethAddress).withdraw(amount, msg.sender)

// instead of this (will not work when you have payable default function)
// WETH(wethAddress).withdraw(amount)
// msg.sender.transfer(amount)
```

Following is the example - 

```js
    /// @dev Sells tokens in exchange for Ether, exchanging them 1:1
    /// @param value Number of tokens to sell
    /// @param user Address of user
    function withdraw(uint value, address user)
        public
    {
        // Balance covers value
        balances[msg.sender] = balances[msg.sender].sub(value);
        totalTokens = totalTokens.sub(value);
        user.transfer(value);
        Withdrawal(msg.sender, value); // can have different event or can change current event
    }
```

Let me know what do you think. I can send pull request if everyone agrees.

**Comment by cag** [comment]
@jdkanani Hey! Thanks for the suggestion :)

We were actually planning to remove EtherToken from this repo and instead refer to the [canonical WETH](https://blog.0xproject.com/canonical-weth-a9aa7d0279dd). There's a package which directly references that [here](https://github.com/gnosis/canonical-weth).

Obviously, that makes doing this sort of extension a bit more tricky, as you'd have to get people to use the extended contract, though I definitely see the use case for this.

One workaround for your use case may just to deploy another contract:

```solidity
contract WETHExt {
    WETH9 public weth;

    constructor(WETH9 _weth) public { weth = _weth; }

    function withdrawTo(address recipient, uint value)
        public
    {
        require(weth.transferFrom(msg.sender, this, value),
            "couldn't transfer from withdrawer");
        this.withdraw(value);
        recipient.transfer(value);
    }
}
```

which can be used like so:

```solidity
weth.approve(wethExt, value);
wethExt.withdrawTo(user, value);
```

Not as efficient, but maybe suitable until WETH is deprecated entirely by ether becoming ERC20 compatible (???)

**Comment by jdkanani** [comment]
We already extended it. No problem at all. Closing the issue now.
