### ISSUE TITLE
Upgrade to Truffle 4.x

### ISSUE THREAD

**Issue by axic** [gnosis/pm-contracts#108]
This repo still relies on Truffle 3.4.11. As you probably know for a while Solidity started issuing deprecation warnings for a lot of old syntax/features which will turn into errors with the 0.5.0 release.

Truffle in the 4.x releases has updated `Assert.sol` to deal with all those requirements. It would be great if Gnosis could upgrade to 4.x and get the benefit of these updates.

Since the Solidity CI also compiles Gnosis contracts, that would make our life much more easier 😉

**Comment by cag** [comment]
Yes, I think this is a sign to switch the active branch to the develop branch now...

**Comment by axic** [comment]
@cag do you have any resolution to the question? :)

**Comment by cag** [comment]
@axic I've decided to make the default branch `development` now. In addition to that, I've resolved all the backwards-compatible 0.5.x type warnings in a PR.

**Comment by axic** [comment]
@cag nice! Should we just rely on `development` then? Also thanks for #110.

**Comment by cag** [comment]
Yes. :+1:
