### ISSUE TITLE
Risk Disclaimer, Privacy Policy, Terms of Service and Imprint button doesn´t work

### ISSUE THREAD

**Issue by MicaelaPesado** [gnosis/pm-contracts#163]
Steps to reproduce:
1. Enter https://trading.staging.gnosisdev.com
2. Click on _Risk Disclaimer, Privacy Policy, Terms of Service_ or _Imprint_ button.
3. Observe

Expected result: 
The usser is redirected correctly to the each page.

Actual result:
The buttons re-charge the page.

Tested on: Chrome, Firefox, Status, Coinbase Wallet.
Mobile: LG nexus 5x
Android version: 8.1.0

**Comment by cag** [comment]
@andre-meyer @mikheevm Is this a pm-trading-ui thing?

**Comment by mikheevm** [comment]
@cag Yep! Thanks

@MicaelaPesado Please post next issues related to the interface to https://github.com/gnosis/pm-trading-ui . Thank you for reporting! We'll fix this

**Comment by MicaelaPesado** [comment]
@mikheevm I'm sorry, ok, I´ll report it in the link, next issues.
