### ISSUE TITLE
addition of state modifier

### ISSUE THREAD

**Issue by josojo** [gnosis/pm-contracts#53]
https://github.com/gnosis/gnosis-contracts/blob/9ae83fd6a2b231801dd39c91d4b554e1db91b7d8/contracts/Markets/StandardMarket.sol#L163

For better readability, I would add the stage modifier        
 atStage(Stages.MarketFunded)

But actually, it is not needed since this.sell would throw anyway, if the contract is in another stage.

How do you guys perceive this kind of issue reports? Pedantic of helpful? Still need to find a workflow.

**Comment by cag** [comment]
We do appreciate it! All pedantry is welcome :P

**Comment by cag** [comment]
This change probably won't get implemented.
