### ISSUE TITLE
Should allow to pass variables to default oracle functions `isOutcomeSet()` and `getOutcome()`

### ISSUE THREAD

**Issue by chumMing** [gnosis/pm-contracts#62]
The default oracle functions (`isOutcomeSet()` and `getOutcome()`) should contain a bytes32 as input. The reason being that right now an oracle contract can only report on a single event as there is no way to request specific information. 

To keep things general it would be nice to pass bytes32 always so that a single oracle can report upon multiple events. 

For example: If i have a tic tac toe contract that plays multiple games in it. And i want to allow prediction markets to link into it. Each game is identified with `keccak256(msg.sender,block.number)` and each time i want to resolve a game i need to specify the game i want to resolve like below.
```
        function isOutcomeSet(bytes32 hash) public constant returns (bool) {
                return(games[hash].isFinished);
        }

        function getOutcome(bytes32 hash) public constant returns (int) {
                return(games[hash].winner);
        }
```

I understand the need to keep this general. But passing nothing will force ppl to deploy alot of contracts to act as intermediaries. Using the bytes32 is the best IMO as its the size of the `keccak256` hash output which is used most often.

**Comment by cag** [comment]
Hmm, I think this is a reasonable request in the discussion of practicality vs purity. However, we expect contact deployment costs to be greatly reduced some time down the line after the Metropolis HF when solidity compiles to use delegate calls for new contract instances: https://www.reddit.com/r/ethereum/comments/6c1jui/delegatecall_forwarders_how_to_save_5098_on/

**Comment by cag** [comment]
So turns out this may have partially inspired the following EIP: https://github.com/ethereum/EIPs/issues/1161

**Comment by cag** [comment]
I'm closing this, since internally, this line of thought has been pursued with https://github.com/gnosis/hg-contracts and there are no plans to change this project in that vein.
